apiVersion: v1
kind: Secret
metadata:
  name: campus-secret
  namespace: default
type: Opaque
data:
  supabase_url: TkVYVF9QVUJMSUNfU1VQQUJBU0VfVVJMPWh0dHBzOi8vZnFyb292ZGdxaXZ3Z29oanV6YWMuc3VwYWJhc2UuY28=
  supabase_anon_key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1aeGNtOXZkbVJuY1dsMmQyZHZhR3AxZW1Gaklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzT0RFME56UTNOVFlzSW1WNGNDSTZNakE1TnpBMU1EYzFObjAuaU5CQjIzQVJjUU5LRlV6VDJvV1RyRnRrREt5UGtQVERKRVJKWVd6THZ3Yw==
  database_url: TkVYVF9QVUJMSUNfU1VQQUJBU0VfVVJMPWh0dHBzOi8vZnFyb292ZGdxaXZ3Z29oanV6YWMuc3VwYWJhc2UuY28=